### ISSUE TITLE
raydown & up event not work on iOS Firefox XRViewer

### ISSUE THREAD

**Issue by Eis4TY** [M-CreativeLab/jsar-dom#11]

**Comment by yorkie** [comment]
May I ask you to try with this: https://m-creativelab.github.io/jsar-dom/, when you "raydown" the cube, it will be green, and back to normal when the "rayup" is fired.

**Comment by Eis4TY** [comment]
> May I ask you to try with this: https://m-creativelab.github.io/jsar-dom/, when you "raydown" the cube, it will be green, and back to normal when the "rayup" is fired.

I see, it works now. Thank you.

**Comment by yorkie** [comment]
Actually I don't change anything :)
